:release-version: 0.0.0
= SKB
v{release-version}
:page-layout: base
:toc: preamble

my Knowledge Base, starting point for several projects

== SKB

The SKB is the entry point or umbrella for a number of my projects, all open source on Github.
SKB is short for _Sven's Knowledge Base_.
I was looking for some acronym (actually abbreviation, since one cannot speak SKB), and this is what I came up with a long time ago (sometimes in 2014 I guess).

This repository contains my databases (acronyms, library, etc.), the source of the SKB website, the source of my personal website, and a Wiki.
The _pom_ file is set to version 1.0.0, which will not change.
Its only purpose is to allow an easy import into Eclipse, which I use as a general purpose editor.

This repository has only a `master` branch, i.e. all updates are published immediately.
No versions are applied.
The websites are generated and published frequently as well, but not for every single push to the `master`.

There are also no _releases_, since all information here is either published in the related websites (see Links below) or used in my other projects.

If you want to improve this repository, please feel free to use the https://github.com/vdmeer/skb/issues[Issue Management]
If I do not address your issues in your time frame, contact me directly.
You'll find a lot of contact information at the bottom of this http://www.vandermeer.de/[page].


=== Source Repository

[cols="20,80", frame=none, grid=rows]
|===

|`https://github.com/vdmeer/skb/tree/master/data[data]`
| Contains the raw data for acronyms and my research library.
All data is written in _YAML_.
The structure of the _YAML_ files, naming conventions, and keys is explained in README files.
The files can be processed with the `SKB-Framework` and the `SKB-DASHBOARD`, to generate for instance collections in _HTML_ or _PDF_.

The content of acronyms and the library is far from being complete neither perfect.
Some files still require work, a lot of _BiBTeX_ and _Biblatex_ sources are missing, and the acronym files are missing some information I still have to add.

|`https://github.com/vdmeer/skb/tree/master/documents[documents]`
| Contains Asciidoctor or _ADOC_ files used to create stand-alone _HTML_ and _PDF_ files and as include files for the SKB-Web.
Most of these files require external settings, for instance a path to (generated) _ADOC_ collection files.
The SKB and sub-projects use the `SKB-Framework` and the `SKB-DASHBOARD` to compile these files.


|`https://github.com/vdmeer/skb/tree/master/sites[sites]`
| Contains the source code for the main SKB Website and my personal website (VDM).
Both websites are written for the Apache Maven plugin `maven-site-plugin`, using the DOXIA renderer and the Asciidoctor plugin.
I have changed the general style (_CSS_) in parts and changed the font to `Roboto Condensed` from Google.
The `SKB-DASHBOARD` is used to generate acronym and library files integrated into the sites.
The sites are then published automatically (SKB) and manually (VDM).

|===

I will add more content whenever I have time and a need for it.
I still have a few things from older SKB databases to add, but I don't have much time.



=== Links

[cols="20,80", frame=none, grid=rows]
|===

| http://www.vandermeer.de[vandermeer.de]
| My personal website, with rather personal information.
If you want to know more about me, this is the place to start at.
It also provides a list of a lot of my online handles, emails, and other IDs.
It is hosted at https://www.powerweb.de/[Powerweb], but without an _SSL_ certificate.
So only plain _HTTP_ will work on this site.
The site is build with _Maven_, the sources are in https://github.com/vdmeer/skb/tree/master/sites/vandermeer[sites/vandermeer].
So the whole site is static, build and published, without any scripts or other interactive means.

The content of the site is licensed as CC-BY-NC, see https://creativecommons.org/licenses/by-nc/4.0/[license] for details.
I added _NC_ because I don't want anyone to make money with my personal information, or my research notes.

| http://vdmeer.github.io/[vdmeer.github.io]
| The same content as the site above, just hosted on Github (so _HTTPS_ will work here!).
Updates happening on the https://github.com/vdmeer/vdmeer.github.io[vdmeer.github.io] repository.
This repository also hosts all other SKB sites, just to make life simple for publishing new information.

The content of the site is licensed as CC-BY-NC, see https://creativecommons.org/licenses/by-nc/4.0/[license] for details.
I added _NC_ because I don't want anyone to make money with my personal information, or my research notes.
Should you have a commercial interest in using any content, please contact me.

| https://vdmeer.github.io/skb/[vdmeer.github.io/skb]
| This is the SKB website, or `SKB-Web`.
It is generated from the sources in https://github.com/vdmeer/skb/tree/master/sites/skb[sites/skb] using _Maven_.

The content of the site is licensed as CC-BY-NC, see https://creativecommons.org/licenses/by-nc/4.0/[license] for details.
As long as you don't sell the content, feel free to to use the research notes, acronyms, and references (research library).
The content of the site is licensed as CC-BY-NC, see https://creativecommons.org/licenses/by-nc/4.0/[license] for details.
I added _NC_ because I don't want anyone to make money with my personal information, or my research notes.

| https://github.com/vdmeer/skb/wiki[Wiki]
| Some pages I can edit fast in a Browser and then pull from Github.
Not sure if I move any of them into this, more permanent and mature, repository.

|===



== Projects



=== Bash

[cols="20,60,20", frame=none, grid=rows]
|===

| SKB-Framework
| A flexible development and application framework
| https://github.com/vdmeer/skb-framework[repo],
http://vdmeer.github.io/skb/framework/[skb-web/framework]

| SKB-Dashboard
| Dashboard for the SKB repository: library, acronyms, etc, based on the SKB-Framework.
| https://github.com/vdmeer/skb-dashboard[repo]

|===



=== Java

[cols="20,60,20", frame=none, grid=rows]
|===


| SKB Java
| A POM and a set of shell scripts, ant tasks/macros, settings, to maintain the Java port of the SKB.
| [repo]

| ASCII Heading
| A simple tool to format headings with various options.
| https://github.com/vdmeer/asciiheading[repo]

| ASCII List
| Many different lists (itemize/unordered, enumerate/ordered, checklist, description) with support for nested lists, using ASCII and UTF characters for labels.
| https://github.com/vdmeer/asciilist[repo]

| ASCII Paragraph
| A simple tool to format paragraphs with indentation, indentation character, alignment, padding (left, right, both), padding characters (left, right, both), and in-line whitespace characters.
| https://github.com/vdmeer/asciiparagraph[repo]

| ASCII Table
| Several implementations of a text table, originally using ASCII and UTF-8 characters for borders.
| https://github.com/vdmeer/asciitable[repo]

| Char Translation
| Set of translators for characters, HTML Elements, and their combinations.
| https://github.com/vdmeer/char-translation[repo]

| ExecS
| A simple set of classes to execute programs from the command line with automated generation of run scripts and flexible applcation option handling.
| https://github.com/vdmeer/execs[repo]

| Interfaces
| Set of interfaces used by other SKB Java projects.
| https://github.com/vdmeer/skb-java-interfaces[repo]

| UTF Themes
| Base elements (lines, corners, borders) and themes for frames, grids, lists (itemize, enumerate).
| https://github.com/vdmeer/ascii-utf-themes[repo]

| SKB Examples
| Examples for the skb-java sub projects.
| https://github.com/vdmeer/skb-java-examples[repo]

| SKB Shell
| A collection of shells for simple command sets, command multi-sets, and multi-threaded versions.
| https://github.com/vdmeer/skb-shell[repo]

| SVG 2 Vector
| Tool to convert SVG to other vector formats (PDF, EMF) w/support for layers.
| https://github.com/vdmeer/svg2vector[repo],
https://bintray.com/vdmeer/generic/svg2vector[bintray],
https://search.maven.org/artifact/de.vandermeer/svg2vector/[maven],
https://mvnrepository.com/artifact/de.vandermeer/svg2vector[mvnrepo]

|===


=== LaTeX

[cols="20,60,20", frame=none, grid=rows]
|===


| Eclipse Cheat Sheet
| A cheat sheet for Eclipse (key bindings and more).
The idea of a cheat sheet came from a discussion on Twitter with https://twitter.com/@noopur2507[@noopur2507] and https://twitter.com/@EclipseJavaIDE[@EclipseJavaIDE].
I had asked an RTFM question and to return the favor of the answers said I do a cheat sheet.
So here it is.
| https://github.com/vdmeer/eclipse-cs[repo], 
https://github.com/vdmeer/eclipse-cs/releases[releases]

| SKB LaTeX
| A LaTeX class for organizing documents, can be integrated into the SKB.
| https://github.com/vdmeer/skb-latex[repo],
https://ctan.org/pkg/skb?lang=en[CTAN]

|===



=== Miscellaneous

[cols="20,60,20", frame=none, grid=rows]
|===

| IPC
| Artifacts (graphics, pptz, text, et.) for InterProcess Communication, aka networking
| https://github.com/vdmeer/ipc[repo], 
http://vdmeer.github.io/skb/ipc/[skb-web/ipc]

|===
