//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== UTF-8 Support



=== IDEs and Editors
Editing source files requires an IDE or editor that can handle UTF-8 and being configured to do so.
Otherwise all UTF-8 characters will be scrambled.

In Eclipse, one can set the respective file, the project or the complete workspace to use UTF-8 encoding.
The default on Windows is CP1252, so make sure to change that before opening any UTF-8 file.
Simply change the text file encoding on the resource.
This will also change the output of the Eclipse console to UTF.

Other editors will have their specific way to configure for UTF file handling.


=== Console and Terminal
Console settings depend very much on the operating system, the terminal program, and the actual font that is used.

In Windows (using `cmd` as shell), change the code page using this command: `chcp 65001`.
In Cygwin, use a terminal that supports UTF-8, for instance the popular `mintty`.
For both, the font `Lucida Console` supports almost all UTF-8 box drawing characters.

Unix and Apple systems are usually better for UTF support.


==== Testing the Console
There are several UTF-8 encoded files one can use to test a console or terminal.
A few of them are listed in the table below.
Simply copy the text of the files into your console and see if the output is as expected.

[cols="30,70", grid=rows, frame=none, %autowidth.stretch, options="header"]
|===
| Source | Description

| link:https://www.w3.org/2001/06/utf-8-test/[W3C] |
A large set of files, all in UTF-8, that can be used to test UTF-8 terminal capabilities.

| link:https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html[W3C UTF-8 Demo] |
This is an example from the W3C using a lot of commonly used UTF-8 characters.

| link:https://www.w3.org/2001/06/utf-8-test/postscript-utf-8.html[W3C UTF-8 PS] |
List of 271 Unicode characters that represent a minimum repertoire that any modern Postscript printer driver receiving plaintext should be able to render.

| link:https://www.cl.cam.ac.uk/~mgk25/ucs/examples/[mgk25] |
Set of UTF-8 files maintained by _Dr Markus Kuhn_, most of which are also hosted on the W3C links shown above.

|===


=== Java
The java compiler might need a reminder to use UTF-8.
The option `-encoding UTF-8` should do the trick.



=== Javadoc
Javadoc has 3 options for dealing with UTF-8 characters.
Encoding for the source (i.e. reading UTF-8 encoded java files),
    `docencoding` for the output (i.e. the html encoding) and
    `charset` for the output (i.e. to tell the browser what character set to use).
All of these options need to be set to UTF-8.

The ANT task for Javadoc has those options.
So using `encoding="UTF-8"`, `docencoding="UTF-8"` and `charset="UTF-8"` should create UTF-8 HTML.



=== JVM
Running a Java program with UTF output might require to set the JVM to UTF as well.
`-Dfile.encoding=UTF-8` should do the trick.

