//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Console and Terminal
Console settings depend very much on
    the operating system,
    the terminal program, and
    the actual font that is used in or with the terminal program.


=== Windows
The console program used here is usually `cmd`.
To activate UTF-8, change the code page `cmd` is using with the command:
----
chcp 65001
----

When using Cygwin in Windows, UTF-8 support depends on the terminal program that is used.
One of the most popular terminals is _mintty_, which supports UTF-8 out of-the-box.

For `cmd` and _Cygwin_, the fonts _Consola_ and `Lucida Console` supports almost all UTF-8 box drawing characters.

