//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== IDEs and Editors
Editing source files requires an IDE or editor that can handle UTF-8 and being configured to do so.
Otherwise all UTF-8 characters will be scrambled.

In Eclipse, one can set the respective file, the project or the complete workspace to use UTF-8 encoding.
The default on Windows is CP1252, so make sure to change that before opening any UTF-8 file.
Simply change the text file encoding on the resource.
This will also change the output of the Eclipse console to UTF.

Other editors will have their specific way to configure for UTF file handling.
