//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Java
The java compiler might need a reminder to use UTF-8 using the option `-encoding UTF-8`.


Javadoc has 3 options for dealing with UTF-8 characters.
Encoding for the source (i.e. reading UTF-8 encoded java files),
    `docencoding` for the output (i.e. the html encoding) and
    `charset` for the output (i.e. to tell the browser what character set to use).
All of these options need to be set to UTF-8.


Running a Java program with UTF output might require to set the JVM to UTF as well.
`-Dfile.encoding=UTF-8` should do the trick.

