//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== My Website

In the past, I did write my own HTMl, then a few versions of a PHP framework for my website.
Overtime, that became very complicated and tedious to update.
Looking for alternatives, I found a lot of frameworks, but most of them were not much simpler to maintain.
Then I discovered the power of the link:https://maven.apache.org/plugins/maven-site-plugin/[Maven site plugin].
A good combination of flexibility (at authoring time) and a flat and simple website (create, for static use).

When the Asciidoctor tool chain did mature, and was added as a language and plugin to the Maven site, I had all I needed.
Asciidoctor allows for all sorts of programming-like features, for instance includes of other files.
This is what I needed.

So I transfered my old site (and related notes) into a Maven site.
I also wrote more text and thought a bit about structuring.
My research library is fully included as well.

The final site is published at link:http://www.vandermeer.de[vandermeer.de] (*no* _HTTPS_)
    and on the link:https://vdmeer.github.io/[skb-web] (*with* _HTTPS_)
