== My Website

In the past, I did write my own HTMl, then a few versions of a PHP framework for my website.
Overtime, that became very complicated and tedious to update.
Looking for alternatives, I found a lot of frameworks, but most of them were not much simplier to maintain.
Then I discovered the power of the link:https://maven.apache.org/plugins/maven-site-plugin/[Maven site plugin].
A good combination of flexibility (at authoring time) and a flat and simple website (create, for static use).

When the Asciidoctor tool chain did mature, and was added as a language and plugin to the Maven site, I had all I needed.
Asciidoctor allows for all sorts of programming-like features, for instance includes of other files.
This is what I needed.

So I transfered my old site (and related notes) inot a Maven site.
I also wrote more text and thought a bit about structuring.
My research library is fully included as well (include from the library folder one level up).

The final site is published at link:http://www.vandermeer.de[vandermeer.de].

