//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

[cols="a", grid=rows, frame=none, %autowidth.stretch]
|===
|include::{library-adoc}/book/1950/neurath-1954-how_machines_work.adoc[]
|include::{library-adoc}/book/1950/ashby-1956-intro_cybernetics.adoc[]
|include::{library-adoc}/book/1960/wiener-1965-cybernetics.adoc[]
|include::{library-adoc}/report/technical/1970/maturana-1970-biology_of_cognition.adoc[]
|include::{library-adoc}/book/1980/maturana-1987-tree_of_knowledge.adoc[]
|include::{library-adoc}/online/2010/dubberly-2015-cybernetics.adoc[]
|===




[appendix]
== Copyright, License, Attribution

Copyright © 2018-2019 Sven van der Meer. All rights reserved.

This work is licensed under a https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike International License].

If you use this work, you can attribute it as follows:

[cols="12,82", frame=none, grid=rows]
|===

| Reference
a| Sven van der Meer: 
_Research Notes - Cybernetics_, {skb-build-month} {skb-build-day}, {skb-build-date} +
available: https://vdmeer.github.io/research-notes.html

| Biblatex
a|
[source, subs="attributes"]
----
@online{vdmeer:skb:rn:ina,
    author = "van der Meer, Sven",
    title  = "Research Notes - Cybernetics",
    url = "https://vdmeer.github.io/research-notes.html",
    date = "{skb-build-date}",
    urldate = "{skb-build-date}"
}
----

| BiBTeX
a|
[source, subs="attributes"]
----
@misc{vdmeer:skb:rn:ina,
    author = "van der Meer, Sven",
    title  = "Research Notes - Cybernetics",
    howpublished = "online",
    url = "https://vdmeer.github.io/research-notes.html",
    year = {skb-build-year}, month = {skb-build-month-lc}, day = {skb-build-day},
    key = "vdm"
}
----

|===

