== Policy-based Management

=== Discussion (taken from vdm/noms/2018)

Understanding the role of policies and the policy-based approach requires some historical context.
The separation of strategy from system (design and process) was first described in (Hansen 1970).

Policy was first used in the 1970’s for security (Bell, 1973) where a relation _W_ provides access control _rules_ to govern system security.
These rules help to govern state transitions on receiving requests.
(Dobson, 1989) states that a system specification describes _what_ a system does while a policy describes how.
Here, the dynamic features are _policy_, _role_, and _control_.

In the mid 1970’s operating systems began using the term policy as an artifact of control (Levin, 1975), where users could influence kernel-space decisions without requiring an expensive kernel to user space switch.
In (Jomier, 1981) the authors separate static and dynamic policies for memory allocation, for static memory allocated at scheduling time with dynamic memory changing with the process.
The policy/mechanism principle for operating system resource allocation is introduced in (Levin, 1975), while (Day, PNA, 2007) explains how this principle can be applied to networks and their management.

Policies are first used in communication systems in (Rouse, 1979) to control sharing resources as rules for _control_.
In (Kamoun, 1981) rules are used to detect and later prevent network congestion.

Event Condition Action (ECA) rules appear first in active databases (Dayal, 1988).
A defined event triggers the evaluation of a defined set of queries (condition) and a defined action is executed if the condition is satisfied.
The processing of rules is strongly associated to database transactions.
Event types for ECA are defined as database operation, temporal, and external notification.
An architecture for an active database management system with CA and ECA policies is described in (McCarthy, 1989).

Policy as a paradigm for network management was defined by Sloman's Imperial College research team.
This work was, at least partially, based on ODP and OSI's network management (Sloman, 1990), also introducing domains.
One of the main focus points was access control (Moffet, 1990).
Policy for network management then is originally defined in (Sloman, 1994), based on earlier work (Robinson, 1988) (Twidle, 1988), as well as the PhD thesis' of Robinson (1988), Moffet (1990), and Twidle (1993).
Originally focusing on access control, the work introduced domains, subject, and target, plus policy categories (and models) and a policy system (with language and tooling) called Ponder.
This is then followed by policy standards, such as the IETF policy framework, DMTF CIM, TMF SID, to name a just view.
A detailed historic perspective on policy can be found in (Boutaba, 2007).

A deep understanding of policy requires study of policy frameworks (Triantafyllopoulou, 2013), approaches (Phan, 2008), and concepts for specifications (Damianou, 2002).
Policies from different domains were also analyzed, such as cognitive radio (Mitola, 2009), security (Han, 2012), network traffic and QoS (Stone, 2001), and XML and open environments (Yagüe, 2006).

Approaches for models that allow multiple PMs in a single PDM have been developed in (Strassner, 2004) and more recently in (Strassner, 2017).
Here, each PM is bound to its specific definitions, for instance an ECA policy is bound to its inherent rule structure, so while being extensible, it is not easy to add new policy models.

A better approach is to specify a formal taxonomy that informs a formal PDM, independent of any specific PM, for instance in (Davy, 2008).

Tool support for syntactic and semantic translation between models can be achieved (Barrett, 2007/GIIS) and (Barrett, 2007/MACE).
However, it is important to note that semantic translation cannot be fully automated.
In (Brennan, 2010) we study inter-domain relationships and policy translation, both important aspects.
We have summarized today’s challenges for policy-based management in [39] and [40].


[cols="a", grid=rows, frame=none, %autowidth.stretch]
|===
|include::{vdmsite-lib-home}/article/1970/hansen-cacm-1970.adoc[]
|include::{vdmsite-lib-home}/report/technical/1970/bell-mitre-1973.adoc[]
|include::{vdmsite-lib-home}/inproceedings/1970/levin-sosp-1975.adoc[]
|include::{vdmsite-lib-home}/article/1970/rouse-tsmc-1979.adoc[]
|include::{vdmsite-lib-home}/article/1980/jomier-tase-1981.adoc[]
|include::{vdmsite-lib-home}/article/1980/kamoun-tacom-1981.adoc[]
|include::{vdmsite-lib-home}/article/1980/dayal-sigmod-1988.adoc[]
|include::{vdmsite-lib-home}/inproceedings/1980/mccarthy-sigmod-1989.adoc[]
|include::{vdmsite-lib-home}/inproceedings/1980/robinson-ftdcs-1988.adoc[]
|include::{vdmsite-lib-home}/inproceedings/1980/twidle-ftdcs-1988.adoc[]
|include::{vdmsite-lib-home}/inproceedings/1980/dobson-ssp-1989.adoc[]
|include::{vdmsite-lib-home}/article/1990/moffet-comcom-1990.adoc[]
|include::{vdmsite-lib-home}/inproceedings/1990/sloman-ftdcs-1990.adoc[]
|include::{vdmsite-lib-home}/article/1990/sloman-jnsm-1994.adoc[]
|include::{vdmsite-lib-home}/article/2000/stone-network-2001.adoc[]
|include::{vdmsite-lib-home}/unpublished/2000/damianou-ic-2002.adoc[]
|include::{vdmsite-lib-home}/book/2000/strassner-pbm-2004.adoc[]
|include::{vdmsite-lib-home}/article/2000/yagüe-jias-2006.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2000/barrett-giis-2007.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2000/barrett-mace-2007.adoc[]
|include::{vdmsite-lib-home}/article/2000/boutaba-jnsm-2007.adoc[]
|include::{vdmsite-lib-home}/article/2000/davy-comcom-2008.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2000/phan-aswec-2008.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2000/mitola-icc-2009.adoc[]
|include::{vdmsite-lib-home}/article/2010/brennan-commag-2010.adoc[]
|include::{vdmsite-lib-home}/article/2010/han-cn-2012.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/triantafyllopoulou-iswcs-2013.adoc[]
|include::{vdmsite-lib-home}/standard/ietf/strassner-supa-2017.adoc[]
|===


=== APEX

[cols="a", grid=rows, frame=none, %autowidth.stretch]
|===
|include::{vdmsite-lib-home}/inproceedings/2010/keeney-cnsm-2014.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/vandermeer-cnsm-2015.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/fallon-noms-2016.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/fallon-im-2017-a.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/fallon-im-2017-b.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/mcnamara-noms-2018.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/vandermeer-noms-2018-a.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/vandermeer-noms-2018-b.adoc[]
|include::{vdmsite-lib-home}/inproceedings/2010/vandermeer-noms-2018-c.adoc[]
|===


