//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== SKB

The SKB is the entry point or umbrella for a number of my projects, all open source on Github.
SKB is short for _Sven's Knowledge Base_.
I was looking for some acronym (actually abbreviation, since one cannot speak SKB), and this is what I came up with a long time ago (sometimes in 2014 I guess).

It is hosted on Github in this link:https://github.com/vdmeer/skb[repository].
The repository contains my databases (acronyms, library, etc.), the source of the SKB website, the source of this website, and a Wiki.


== Projects - Bash

[cols="20,60,20", frame=none, grid=rows]
|===

| SKB-Framework
| A flexible development and application framework
| https://github.com/vdmeer/skb-framework[repo],
http://vdmeer.github.io/skb/framework/[skb-web/framework]

| SKB-Dashboard
| Dashboard for the SKB repository: library, acronyms, etc, based on the SKB-Framework.
| https://github.com/vdmeer/skb-dashboard[repo]

|===




== Projects - Java

[cols="20,60,20", frame=none, grid=rows]
|===


| SKB Java
| A POM and a set of shell scripts, ant tasks/macros, settings, to maintain the Java port of the SKB.
| https://github.com/vdmeer/skb-java[repo]

| ASCII Heading
| A simple tool to format headings with various options.
| https://github.com/vdmeer/asciiheading[repo]

| ASCII List
| Many different lists (itemize/unordered, enumerate/ordered, checklist, description) with support for nested lists, using ASCII and UTF characters for labels.
| https://github.com/vdmeer/asciilist[repo]

| ASCII Paragraph
| A simple tool to format paragraphs with indentation, indentation character, alignment, padding (left, right, both), padding characters (left, right, both), and in-line whitespace characters.
| https://github.com/vdmeer/asciiparagraph[repo]

| ASCII Table
| Several implementations of a text table, originally using ASCII and UTF-8 characters for borders.
| https://github.com/vdmeer/asciitable[repo]

| Char Translation
| Set of translators for characters, HTML Elements, and their combinations.
| https://github.com/vdmeer/char-translation[repo]

| ExecS
| A simple set of classes to execute programs from the command line with automated generation of run scripts and flexible applcation option handling.
| https://github.com/vdmeer/execs[repo]

| Interfaces
| Set of interfaces used by other SKB Java projects.
| https://github.com/vdmeer/skb-java-interfaces[repo]

| UTF Themes
| Base elements (lines, corners, borders) and themes for frames, grids, lists (itemize, enumerate).
| https://github.com/vdmeer/ascii-utf-themes[repo]

| SKB Examples
| Examples for the skb-java sub projects.
| https://github.com/vdmeer/skb-java-examples[repo]

| SKB Shell
| A collection of shells for simple command sets, command multi-sets, and multi-threaded versions.
| https://github.com/vdmeer/skb-shell[repo]

| SVG 2 Vector
| Tool to convert SVG to other vector formats (PDF, EMF) w/support for layers.
| https://github.com/vdmeer/svg2vector[repo],
https://bintray.com/vdmeer/generic/svg2vector[bintray],
https://search.maven.org/artifact/de.vandermeer/svg2vector/[maven],
https://mvnrepository.com/artifact/de.vandermeer/svg2vector[mvnrepo]

|===




== Projects - LaTeX

[cols="20,60,20", frame=none, grid=rows]
|===


| Eclipse Cheat Sheet
| A cheat sheet for Eclipse (key bindings and more).
The idea of a cheat sheet came from a discussion on Twitter with https://twitter.com/@noopur2507[@noopur2507] and https://twitter.com/@EclipseJavaIDE[@EclipseJavaIDE].
I had asked an RTFM question and to return the favor of the answers said I do a cheat sheet.
So here it is.
| https://github.com/vdmeer/eclipse-cs[repo], 
https://github.com/vdmeer/eclipse-cs/releases[releases]

| SKB LaTeX
| A LaTeX class for organizing documents, can be integrated into the SKB.
| https://github.com/vdmeer/skb-latex[repo],
https://ctan.org/pkg/skb?lang=en[CTAN]

|===



== Projects - Miscellaneous

[cols="20,60,20", frame=none, grid=rows]
|===

| IPC
| Artifacts (graphics, pptx, text, et.) for Inter-Process Communication, aka networking
| https://github.com/vdmeer/ipc[repo], 
http://vdmeer.github.io/skb/ipc/[skb-web/ipc]

|===


== SKB History
It all started sometimes in the late 1990s, when I got my own domain (as a birthday present from very good friends).
We started web development, first static HTML, then PHP.
While working as a researcher and PhD student, I wanted to have a list of publications on my website.
Later acronyms, foto collection, diaries, and other 'stuff'.

Later in Ireland, I started programming and developing in Java.
Github became available, and I started hosting some projects on Github.
Those projects (PHP and Java), evolved, some I did not continue.
The PHP backend for my site was a lot of work.
It was very good for processing data at runtime, but it turned out to be hard to add new data (for instanc a new publication).
So sometimes around 2011 I stopped maintaining the data, thus the whole project and site hibernated.

In 2018 then I turned back to this problem, partially because I had an idea how to realize the whole set differently.
for our APEX engine (and earlier in some SKB Java projects), I had experimented with the Maven Site plugin.
I also used the Asciidoctor toolchain heavily.
Combining both seemed a good idea.
Then I found a way to maintain my data in a non-proprietary form (text files) that also allows to process them for other purposes (such as a website).
And now we are here.
