//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== SKB - Research Library (Data)

This is the raw data of my research library.
The organization is relatively easy.
All library items are in directories.
Directory names are mostly Biblatex entry types.
Larger collections, for instance _in-proceedings_, have sub-directories for decades.

Individual items have a YAML file with all details.
From the YAML file, ADOC, BiBTeX, and Biblatex files are created using the `SKB-Dashboard`.
Other output formats can be added easily.

This library data is then used in documents and sites to build lists and collections.
This is done using the Asciidoctor tool chain.
I take my own publications for instance for my personal website, and also generate standalone _HTML_ and _PDF_ documents.

For compiled versions, stand-alone documents, and more information see:

* `document` directory in this repository https://github.com/vdmeer/skb/tree/master/documents/library[documents/library]
* compiled versions are also linked in the link:https://vdmeer.github.io/skb/library.html[skb-web] (_HTML_ and _PDF_ versions)
