//
// ============LICENSE_START=======================================================
//  Copyright (C) 2018 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the CREATIVE COMMONS ATTRIBUTION 4.0 INTERNATIONAL LICENSE
// Full license text at https://creativecommons.org/licenses/by/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== SKB - Research Library (Data)

This is my research library.
I used to have several places for references and notes, from SQL databases to JSON and YAML files, and of course hand-written notes.
Now I am consolidating all of that in this library.

The organization is relatively easy.
All library items are in directories.
Directory names are mostly BibLaTeX entry types.
Larger collections, for instance _in-proceedings_, have sub-directories for decades.

Individual items have a YAML files with all details.
From the YAML file, ADOC, BiBTeX, and Biblatex files are created using the SKB-Dashboard.
Other output formats can be added easily.

This library data is then used in documents and sites to build lists and collections.
This is done using the Asciidoctor tool chain.
I take my own publications for instance for my personal website.
Some of the topics I use there as well, as research notes.
And I do generate HTML versions and host them on my GH pages.
On my local server I also have a library with PDFs and other artifacts.
The build script `_build.sh` builds the files for me.

For compiled versions see the document directory in this repository.
