//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== SKB - Research Library (Data) - Standards

Standards and publications by Standard Defining Organizations (SDO).
The naming scheme for in-standards varies with the standardization organization.
Entries are grouped by standard organization.

Standard Defining Organizations (SDO) use different mechanism for versioning their standards.
In the IETF, standards (here called Request For Comment, RFC) are numbered and higher number standards can obsolete lower number standards.
In the ITU, standards (here called recommendations) are often versioned using the year of publication or an integer as extension to the standard.
ISO is using a similar mechanism.
The OMG uses a version number for their standards.
The entries here (as well as Biblatex and BibTeX files) will always refer to the latest version (pending editing updates).
Publications using the bibliography should copy, rather than reference, the files, to avoid wrong citations.

For compiled versions, stand-alone documents, and more information see:

* `document` directory in this repository https://github.com/vdmeer/skb/tree/master/documents/library[documents/library]
* compiled versions are also linked in the link:https://vdmeer.github.io/skb/library.html[skb-web] (_HTML_ and _PDF_ versions)
